name: local
root: ./
tmux_options: -2

windows:
  - editor:
      layout: cbb6,270x58,0,0{134x58,0,0[134x29,0,0,16,134x28,0,30,20],135x58,135,0,18}
      panes:
        - commond:
            - clear
        - console:
            - clear
        - emacs:
            - clear
            - e
  - run:
      layout: even-horizon
      panes:
        - edit:
            - clear
        - app-log:
            - clear
