(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/") t)
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)

(package-initialize)
;;(package-refresh-contents)

(package-install 'ace-jump-mode)
(package-install 'anzu)
(package-install 'atom-dark-theme)
(package-install 'bind-key)
(package-install 'company)
(package-install 'csv-mode)
(package-install 'diminish)
(package-install 'flycheck)
(package-install 'flycheck-d-unittest)
(package-install 'flycheck-tip)
(package-install 'flymake-cursor)
(package-install 'git-gutter+)
(package-install 'gitconfig-mode)
(package-install 'goto-chg)
(package-install 'helm)
(package-install 'helm-ag)
(package-install 'helm-descbinds)
(package-install 'helm-gtags)
(package-install 'helm-projectile)
(package-install 'js2-mode)
(package-install 'magit)
(package-install 'markdown-mode)
(package-install 'nginx-mode)
(package-install 'powerline)
(package-install 'projectile-rails)
(package-install 'rainbow-delimiters)
(package-install 'rainbow-mode)
(package-install 'ruby-block)
(package-install 'ruby-electric)
(package-install 'ruby-end)
(package-install 'sass-mode)
(package-install 'scss-mode)
(package-install 'slim-mode)
(package-install 'smart-compile)
(package-install 'smart-mode-line)
(package-install 'smartrep)
(package-install 'ssh-config-mode)
(package-install 'string-inflection)
(package-install 'undo-tree)
(package-install 'undohist)
(package-install 'use-package)
(package-install 'web-mode)
(package-install 'which-key)
(package-install 'yaml-mode)
(package-install 'yascroll)
(package-install 'yasnippet)
;; (Package-install 'anything)
;; (package-install 'auto-complete)
;; (package-install 'auto-complete-clang)
;; (package-install 'point-undo)
